### ISSUE TITLE
Server handling exception

### ISSUE THREAD

**Issue by wangshuaicumt** [ASFHyP3/hyp3#2410] opened 2024-09-05 02:22 UTC
Dear Hyp3 team, 

Hello, when I uploaded the Hyp3 task yesterday, the download link returned had many errors. 

The following is the log file. Thank you for your help.

[log.txt](https://github.com/user-attachments/files/16883072/log.txt)

**Comment by asjohnston-asf** [comment] 2024-09-06 16:23
Duplicate of https://github.com/ASFHyP3/hyp3-sdk/issues/294

**Closed by asjohnston-asf** 2024-09-06 16:23 UTC
